<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Station</AssemblyName>
    <RootNamespace>StationApp</RootNamespace>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="RouteManager.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="RouteManager.cs" />
  </ItemGroup>

  <ItemGroup>
    <!-- SerialPort (связь с Arduino) -->
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

</Project>
